server {
    listen 80;
    listen [::]:80;
    server_name capt-laundry.treeckle.com www.capt-laundry.treeckle.com;
    server_tokens off;
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    location / {
        return 301 https://capt-laundry.treeckle.com$request_uri;
    }
}

server {
    listen 443 default_server ssl;
    listen [::]:443 ssl;
    server_name capt-laundry.treeckle.com;
    ssl_certificate /etc/letsencrypt/live/capt-laundry.treeckle.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/capt-laundry.treeckle.com/privkey.pem;

    location /api/sensor/ {
        proxy_pass http://laundry-bot:5001/;
    }

    location / {
        proxy_pass http://laundry-bot:3000;
    }
}